name: Demo Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY_HOST: containers-lab.pkg.github.com

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t $REGISTRY_HOST/sweethaven-village/issue4235a:fromb .

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_HOST -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push $REGISTRY_HOST/sweethaven-village/issue4235a:fromb
